// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth_service.proto

package com.codersontrang.protos;

public final class AuthService {
  private AuthService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogonRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogonRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    boolean hasTicket();
    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    java.lang.String getTicket();
    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    com.google.protobuf.ByteString
        getTicketBytes();

    /**
     * <code>optional string customer_id = 2;</code>
     */
    boolean hasCustomerId();
    /**
     * <code>optional string customer_id = 2;</code>
     */
    java.lang.String getCustomerId();
    /**
     * <code>optional string customer_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    /**
     * <code>required string target = 3;</code>
     *
     * <pre>
     * SOCIAL = 1; TRADING = 2;
     * </pre>
     */
    boolean hasTarget();
    /**
     * <code>required string target = 3;</code>
     *
     * <pre>
     * SOCIAL = 1; TRADING = 2;
     * </pre>
     */
    java.lang.String getTarget();
    /**
     * <code>required string target = 3;</code>
     *
     * <pre>
     * SOCIAL = 1; TRADING = 2;
     * </pre>
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    /**
     * <code>required string service_type = 4;</code>
     *
     * <pre>
     *1: FX account, 4: CFD account, 7: Social account
     * </pre>
     */
    boolean hasServiceType();
    /**
     * <code>required string service_type = 4;</code>
     *
     * <pre>
     *1: FX account, 4: CFD account, 7: Social account
     * </pre>
     */
    java.lang.String getServiceType();
    /**
     * <code>required string service_type = 4;</code>
     *
     * <pre>
     *1: FX account, 4: CFD account, 7: Social account
     * </pre>
     */
    com.google.protobuf.ByteString
        getServiceTypeBytes();
  }
  /**
   * Protobuf type {@code LogonRequest}
   *
   * <pre>
   *Logon request
   * </pre>
   */
  public static final class LogonRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LogonRequest)
      LogonRequestOrBuilder {
    // Use LogonRequest.newBuilder() to construct.
    private LogonRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogonRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogonRequest defaultInstance;
    public static LogonRequest getDefaultInstance() {
      return defaultInstance;
    }

    public LogonRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogonRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              ticket_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              customerId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              target_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              serviceType_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codersontrang.protos.AuthService.internal_static_LogonRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codersontrang.protos.AuthService.internal_static_LogonRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codersontrang.protos.AuthService.LogonRequest.class, com.codersontrang.protos.AuthService.LogonRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<LogonRequest> PARSER =
        new com.google.protobuf.AbstractParser<LogonRequest>() {
      public LogonRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogonRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogonRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TICKET_FIELD_NUMBER = 1;
    private java.lang.Object ticket_;
    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    public boolean hasTicket() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    public java.lang.String getTicket() {
      java.lang.Object ref = ticket_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ticket_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTicketBytes() {
      java.lang.Object ref = ticket_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_ID_FIELD_NUMBER = 2;
    private java.lang.Object customerId_;
    /**
     * <code>optional string customer_id = 2;</code>
     */
    public boolean hasCustomerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string customer_id = 2;</code>
     */
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string customer_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGET_FIELD_NUMBER = 3;
    private java.lang.Object target_;
    /**
     * <code>required string target = 3;</code>
     *
     * <pre>
     * SOCIAL = 1; TRADING = 2;
     * </pre>
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string target = 3;</code>
     *
     * <pre>
     * SOCIAL = 1; TRADING = 2;
     * </pre>
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string target = 3;</code>
     *
     * <pre>
     * SOCIAL = 1; TRADING = 2;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_TYPE_FIELD_NUMBER = 4;
    private java.lang.Object serviceType_;
    /**
     * <code>required string service_type = 4;</code>
     *
     * <pre>
     *1: FX account, 4: CFD account, 7: Social account
     * </pre>
     */
    public boolean hasServiceType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string service_type = 4;</code>
     *
     * <pre>
     *1: FX account, 4: CFD account, 7: Social account
     * </pre>
     */
    public java.lang.String getServiceType() {
      java.lang.Object ref = serviceType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string service_type = 4;</code>
     *
     * <pre>
     *1: FX account, 4: CFD account, 7: Social account
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServiceTypeBytes() {
      java.lang.Object ref = serviceType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ticket_ = "";
      customerId_ = "";
      target_ = "";
      serviceType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTicket()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTarget()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServiceType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTicketBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCustomerIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTargetBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getServiceTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTicketBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCustomerIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTargetBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getServiceTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.codersontrang.protos.AuthService.LogonRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codersontrang.protos.AuthService.LogonRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.LogonRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codersontrang.protos.AuthService.LogonRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.LogonRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.codersontrang.protos.AuthService.LogonRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.LogonRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.codersontrang.protos.AuthService.LogonRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.LogonRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.codersontrang.protos.AuthService.LogonRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.codersontrang.protos.AuthService.LogonRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogonRequest}
     *
     * <pre>
     *Logon request
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogonRequest)
        com.codersontrang.protos.AuthService.LogonRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.codersontrang.protos.AuthService.internal_static_LogonRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.codersontrang.protos.AuthService.internal_static_LogonRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.codersontrang.protos.AuthService.LogonRequest.class, com.codersontrang.protos.AuthService.LogonRequest.Builder.class);
      }

      // Construct using com.codersontrang.protos.AuthService.LogonRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ticket_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        customerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        target_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        serviceType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.codersontrang.protos.AuthService.internal_static_LogonRequest_descriptor;
      }

      public com.codersontrang.protos.AuthService.LogonRequest getDefaultInstanceForType() {
        return com.codersontrang.protos.AuthService.LogonRequest.getDefaultInstance();
      }

      public com.codersontrang.protos.AuthService.LogonRequest build() {
        com.codersontrang.protos.AuthService.LogonRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.codersontrang.protos.AuthService.LogonRequest buildPartial() {
        com.codersontrang.protos.AuthService.LogonRequest result = new com.codersontrang.protos.AuthService.LogonRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ticket_ = ticket_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.customerId_ = customerId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.target_ = target_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serviceType_ = serviceType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.codersontrang.protos.AuthService.LogonRequest) {
          return mergeFrom((com.codersontrang.protos.AuthService.LogonRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.codersontrang.protos.AuthService.LogonRequest other) {
        if (other == com.codersontrang.protos.AuthService.LogonRequest.getDefaultInstance()) return this;
        if (other.hasTicket()) {
          bitField0_ |= 0x00000001;
          ticket_ = other.ticket_;
          onChanged();
        }
        if (other.hasCustomerId()) {
          bitField0_ |= 0x00000002;
          customerId_ = other.customerId_;
          onChanged();
        }
        if (other.hasTarget()) {
          bitField0_ |= 0x00000004;
          target_ = other.target_;
          onChanged();
        }
        if (other.hasServiceType()) {
          bitField0_ |= 0x00000008;
          serviceType_ = other.serviceType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTicket()) {
          
          return false;
        }
        if (!hasTarget()) {
          
          return false;
        }
        if (!hasServiceType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.codersontrang.protos.AuthService.LogonRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.codersontrang.protos.AuthService.LogonRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object ticket_ = "";
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public boolean hasTicket() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public java.lang.String getTicket() {
        java.lang.Object ref = ticket_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ticket_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTicketBytes() {
        java.lang.Object ref = ticket_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ticket_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public Builder setTicket(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ticket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public Builder clearTicket() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ticket_ = getDefaultInstance().getTicket();
        onChanged();
        return this;
      }
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public Builder setTicketBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ticket_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object customerId_ = "";
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public boolean hasCustomerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            customerId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public Builder clearCustomerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        customerId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object target_ = "";
      /**
       * <code>required string target = 3;</code>
       *
       * <pre>
       * SOCIAL = 1; TRADING = 2;
       * </pre>
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string target = 3;</code>
       *
       * <pre>
       * SOCIAL = 1; TRADING = 2;
       * </pre>
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            target_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string target = 3;</code>
       *
       * <pre>
       * SOCIAL = 1; TRADING = 2;
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string target = 3;</code>
       *
       * <pre>
       * SOCIAL = 1; TRADING = 2;
       * </pre>
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string target = 3;</code>
       *
       * <pre>
       * SOCIAL = 1; TRADING = 2;
       * </pre>
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000004);
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <code>required string target = 3;</code>
       *
       * <pre>
       * SOCIAL = 1; TRADING = 2;
       * </pre>
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        target_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serviceType_ = "";
      /**
       * <code>required string service_type = 4;</code>
       *
       * <pre>
       *1: FX account, 4: CFD account, 7: Social account
       * </pre>
       */
      public boolean hasServiceType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string service_type = 4;</code>
       *
       * <pre>
       *1: FX account, 4: CFD account, 7: Social account
       * </pre>
       */
      public java.lang.String getServiceType() {
        java.lang.Object ref = serviceType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string service_type = 4;</code>
       *
       * <pre>
       *1: FX account, 4: CFD account, 7: Social account
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServiceTypeBytes() {
        java.lang.Object ref = serviceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string service_type = 4;</code>
       *
       * <pre>
       *1: FX account, 4: CFD account, 7: Social account
       * </pre>
       */
      public Builder setServiceType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string service_type = 4;</code>
       *
       * <pre>
       *1: FX account, 4: CFD account, 7: Social account
       * </pre>
       */
      public Builder clearServiceType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serviceType_ = getDefaultInstance().getServiceType();
        onChanged();
        return this;
      }
      /**
       * <code>required string service_type = 4;</code>
       *
       * <pre>
       *1: FX account, 4: CFD account, 7: Social account
       * </pre>
       */
      public Builder setServiceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serviceType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LogonRequest)
    }

    static {
      defaultInstance = new LogonRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LogonRequest)
  }

  public interface LogoutRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogoutRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    boolean hasTicket();
    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    java.lang.String getTicket();
    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    com.google.protobuf.ByteString
        getTicketBytes();

    /**
     * <code>optional string customer_id = 2;</code>
     */
    boolean hasCustomerId();
    /**
     * <code>optional string customer_id = 2;</code>
     */
    java.lang.String getCustomerId();
    /**
     * <code>optional string customer_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();
  }
  /**
   * Protobuf type {@code LogoutRequest}
   *
   * <pre>
   *Logout request
   * </pre>
   */
  public static final class LogoutRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LogoutRequest)
      LogoutRequestOrBuilder {
    // Use LogoutRequest.newBuilder() to construct.
    private LogoutRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogoutRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogoutRequest defaultInstance;
    public static LogoutRequest getDefaultInstance() {
      return defaultInstance;
    }

    public LogoutRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogoutRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              ticket_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              customerId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codersontrang.protos.AuthService.internal_static_LogoutRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codersontrang.protos.AuthService.internal_static_LogoutRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codersontrang.protos.AuthService.LogoutRequest.class, com.codersontrang.protos.AuthService.LogoutRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<LogoutRequest> PARSER =
        new com.google.protobuf.AbstractParser<LogoutRequest>() {
      public LogoutRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogoutRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogoutRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TICKET_FIELD_NUMBER = 1;
    private java.lang.Object ticket_;
    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    public boolean hasTicket() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    public java.lang.String getTicket() {
      java.lang.Object ref = ticket_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ticket_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ticket = 1;</code>
     *
     * <pre>
     *token key get after login
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTicketBytes() {
      java.lang.Object ref = ticket_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_ID_FIELD_NUMBER = 2;
    private java.lang.Object customerId_;
    /**
     * <code>optional string customer_id = 2;</code>
     */
    public boolean hasCustomerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string customer_id = 2;</code>
     */
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string customer_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ticket_ = "";
      customerId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTicket()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTicketBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCustomerIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTicketBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCustomerIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.codersontrang.protos.AuthService.LogoutRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codersontrang.protos.AuthService.LogoutRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.LogoutRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codersontrang.protos.AuthService.LogoutRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.LogoutRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.codersontrang.protos.AuthService.LogoutRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.LogoutRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.codersontrang.protos.AuthService.LogoutRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.LogoutRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.codersontrang.protos.AuthService.LogoutRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.codersontrang.protos.AuthService.LogoutRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogoutRequest}
     *
     * <pre>
     *Logout request
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogoutRequest)
        com.codersontrang.protos.AuthService.LogoutRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.codersontrang.protos.AuthService.internal_static_LogoutRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.codersontrang.protos.AuthService.internal_static_LogoutRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.codersontrang.protos.AuthService.LogoutRequest.class, com.codersontrang.protos.AuthService.LogoutRequest.Builder.class);
      }

      // Construct using com.codersontrang.protos.AuthService.LogoutRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ticket_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        customerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.codersontrang.protos.AuthService.internal_static_LogoutRequest_descriptor;
      }

      public com.codersontrang.protos.AuthService.LogoutRequest getDefaultInstanceForType() {
        return com.codersontrang.protos.AuthService.LogoutRequest.getDefaultInstance();
      }

      public com.codersontrang.protos.AuthService.LogoutRequest build() {
        com.codersontrang.protos.AuthService.LogoutRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.codersontrang.protos.AuthService.LogoutRequest buildPartial() {
        com.codersontrang.protos.AuthService.LogoutRequest result = new com.codersontrang.protos.AuthService.LogoutRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ticket_ = ticket_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.customerId_ = customerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.codersontrang.protos.AuthService.LogoutRequest) {
          return mergeFrom((com.codersontrang.protos.AuthService.LogoutRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.codersontrang.protos.AuthService.LogoutRequest other) {
        if (other == com.codersontrang.protos.AuthService.LogoutRequest.getDefaultInstance()) return this;
        if (other.hasTicket()) {
          bitField0_ |= 0x00000001;
          ticket_ = other.ticket_;
          onChanged();
        }
        if (other.hasCustomerId()) {
          bitField0_ |= 0x00000002;
          customerId_ = other.customerId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTicket()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.codersontrang.protos.AuthService.LogoutRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.codersontrang.protos.AuthService.LogoutRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object ticket_ = "";
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public boolean hasTicket() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public java.lang.String getTicket() {
        java.lang.Object ref = ticket_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ticket_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTicketBytes() {
        java.lang.Object ref = ticket_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ticket_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public Builder setTicket(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ticket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public Builder clearTicket() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ticket_ = getDefaultInstance().getTicket();
        onChanged();
        return this;
      }
      /**
       * <code>required string ticket = 1;</code>
       *
       * <pre>
       *token key get after login
       * </pre>
       */
      public Builder setTicketBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ticket_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object customerId_ = "";
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public boolean hasCustomerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            customerId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public Builder clearCustomerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string customer_id = 2;</code>
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        customerId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LogoutRequest)
    }

    static {
      defaultInstance = new LogoutRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LogoutRequest)
  }

  public interface HeartbeetEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartbeetEvent)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code HeartbeetEvent}
   *
   * <pre>
   *Heartbeat
   * </pre>
   */
  public static final class HeartbeetEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HeartbeetEvent)
      HeartbeetEventOrBuilder {
    // Use HeartbeetEvent.newBuilder() to construct.
    private HeartbeetEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartbeetEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartbeetEvent defaultInstance;
    public static HeartbeetEvent getDefaultInstance() {
      return defaultInstance;
    }

    public HeartbeetEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartbeetEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.codersontrang.protos.AuthService.internal_static_HeartbeetEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.codersontrang.protos.AuthService.internal_static_HeartbeetEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.codersontrang.protos.AuthService.HeartbeetEvent.class, com.codersontrang.protos.AuthService.HeartbeetEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartbeetEvent> PARSER =
        new com.google.protobuf.AbstractParser<HeartbeetEvent>() {
      public HeartbeetEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartbeetEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartbeetEvent> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.codersontrang.protos.AuthService.HeartbeetEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codersontrang.protos.AuthService.HeartbeetEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.HeartbeetEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.codersontrang.protos.AuthService.HeartbeetEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.HeartbeetEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.codersontrang.protos.AuthService.HeartbeetEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.HeartbeetEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.codersontrang.protos.AuthService.HeartbeetEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.codersontrang.protos.AuthService.HeartbeetEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.codersontrang.protos.AuthService.HeartbeetEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.codersontrang.protos.AuthService.HeartbeetEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartbeetEvent}
     *
     * <pre>
     *Heartbeat
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartbeetEvent)
        com.codersontrang.protos.AuthService.HeartbeetEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.codersontrang.protos.AuthService.internal_static_HeartbeetEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.codersontrang.protos.AuthService.internal_static_HeartbeetEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.codersontrang.protos.AuthService.HeartbeetEvent.class, com.codersontrang.protos.AuthService.HeartbeetEvent.Builder.class);
      }

      // Construct using com.codersontrang.protos.AuthService.HeartbeetEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.codersontrang.protos.AuthService.internal_static_HeartbeetEvent_descriptor;
      }

      public com.codersontrang.protos.AuthService.HeartbeetEvent getDefaultInstanceForType() {
        return com.codersontrang.protos.AuthService.HeartbeetEvent.getDefaultInstance();
      }

      public com.codersontrang.protos.AuthService.HeartbeetEvent build() {
        com.codersontrang.protos.AuthService.HeartbeetEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.codersontrang.protos.AuthService.HeartbeetEvent buildPartial() {
        com.codersontrang.protos.AuthService.HeartbeetEvent result = new com.codersontrang.protos.AuthService.HeartbeetEvent(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.codersontrang.protos.AuthService.HeartbeetEvent) {
          return mergeFrom((com.codersontrang.protos.AuthService.HeartbeetEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.codersontrang.protos.AuthService.HeartbeetEvent other) {
        if (other == com.codersontrang.protos.AuthService.HeartbeetEvent.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.codersontrang.protos.AuthService.HeartbeetEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.codersontrang.protos.AuthService.HeartbeetEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HeartbeetEvent)
    }

    static {
      defaultInstance = new HeartbeetEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HeartbeetEvent)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogonRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LogonRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogoutRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LogoutRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartbeetEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartbeetEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022auth_service.proto\032\020auth_model.proto\"Y" +
      "\n\014LogonRequest\022\016\n\006ticket\030\001 \002(\t\022\023\n\013custom" +
      "er_id\030\002 \001(\t\022\016\n\006target\030\003 \002(\t\022\024\n\014service_t" +
      "ype\030\004 \002(\t\"4\n\rLogoutRequest\022\016\n\006ticket\030\001 \002" +
      "(\t\022\023\n\013customer_id\030\002 \001(\t\"\020\n\016HeartbeetEven" +
      "tB\032\n\030com.codersontrang.protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          .AuthModel.getDescriptor(),
        }, assigner);
    internal_static_LogonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LogonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LogonRequest_descriptor,
        new java.lang.String[] { "Ticket", "CustomerId", "Target", "ServiceType", });
    internal_static_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LogoutRequest_descriptor,
        new java.lang.String[] { "Ticket", "CustomerId", });
    internal_static_HeartbeetEvent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HeartbeetEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HeartbeetEvent_descriptor,
        new java.lang.String[] { });
    AuthModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
